### PR TITLE
feat: add --version and --diagnostic top-level options

### LINKED ISSUE #549: Augment `everyvoice` with `--version` & `--diagnostic`
Add options to `everyvoice` to help write issues.  Inspired by `bat --diagnostic`, add `--version` that would simply output the version of everyvoice the user is currently using.  A more verbose version `--diagnostic` where we could print os version, environment relevant variables, something equivalent to `pip list` ... and whatever information could be useful for debugging.

Eric suggests that the output be in markdown to make it easily copyable.

### PR DESCRIPTION
**Pull request by joanise**
### PR Goal? 

add `--version` and `--diagnostic` top-level options to EV.

### Fixes? 

Fixes #549

### Priority? 

beta

### Tests added? 

ues

### How to test? 

Run
`everyvoice --version` and `everyvoice --diagnostic`

### Confidence? 

high

### CODE REVIEW

**Comment by marctessier** [comment]
Works great , this will be very handy when debugging. 

```
(EveryVoice_dev.ej_549) [U20-GPSC5]:$ everyvoice --version
0.1.0a3

(EveryVoice_dev.ej_549) [U20-GPSC5]:$ everyvoice --diagnostic
EveryVoice Diagnostic information
EveryVoice version: 0.1.0a3
Python version: 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:24:24) [GCC 13.3.0]
System: Linux 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64
pip freeze:
absl-py==2.1.0
aiofiles==23.2.1
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.6.2.post1
anytree==2.12.1
arrow==1.3.0
async-timeout==4.0.3
attrs==24.2.0
audioread==3.0.1
black==24.10.0
certifi==2024.8.30
cffi==1.17.1
cfgv==3.4.0
charset-normalizer==3.4.0
click==8.1.7
clipdetect==0.1.4
coloredlogs==15.0.1
contourpy==1.3.0
cycler==0.12.1
Cython==3.0.11
decorator==5.1.1
deepdiff==8.0.1
distlib==0.3.9
dnspython==2.7.0
editdistance==0.8.1
einops==0.5.0
email_validator==2.2.0
et_xmlfile==2.0.0
-e git+https://github.com/EveryVoiceTTS/EveryVoice.git@b22a897a897bf51cf691be4f6822f69b29db49ad#egg=everyvoice
exceptiongroup==1.2.2
fastapi==0.115.4
ffmpy==0.4.0
filelock==3.16.1
flake8==7.1.1
fonttools==4.54.1
frozenlist==1.5.0
fsspec==2024.10.0
g2p==2.1.1
gitlint-core==0.19.1
gradio==5.4.0
gradio_client==1.4.2
grapheme==0.6.0
grpcio==1.67.1
h11==0.14.0
httpcore==1.0.6
httpx==0.27.2
huggingface-hub==0.26.2
humanfriendly==10.0
identify==2.6.1
idna==3.10
iniconfig==2.0.0
ipatok==0.4.2
isort==5.13.2
Jinja2==3.1.4
joblib==1.4.2
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kiwisolver==1.4.7
librosa==0.9.2
lightning==2.4.0
lightning-utilities==0.11.8
lit==18.1.8
llvmlite==0.43.0
loguru==0.6.0
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mccabe==0.7.0
mdurl==0.1.2
merge-args==0.1.5
mpmath==1.3.0
multidict==6.1.0
munkres==1.1.4
mypy==1.13.0
mypy-extensions==1.0.0
networkx==3.4.2
nltk==3.9.1
nodeenv==1.9.1
numba==0.60.0
numpy==1.26.4
openpyxl==3.1.5
orderly-set==5.2.2
orjson==3.10.10
packaging==24.1
pandas==2.2.3
panphon==0.20.0
pathspec==0.12.1
pep440==0.1.2
pillow==11.0.0
platformdirs==4.3.6
pluggy==1.5.0
pooch==1.8.2
pre_commit==4.0.1
prompt_toolkit==3.0.48
propcache==0.2.0
protobuf==4.25.5
pycodestyle==2.12.1
pycountry==22.3.5
pycparser==2.22
pydantic==2.7.4
pydantic_core==2.18.4
pydub==0.25.1
pyflakes==3.2.0
Pygments==2.18.0
pympi-ling==1.70.2
pyparsing==3.2.0
pysdtw==0.0.5
pytest==7.4.4
python-dateutil==2.9.0.post0
python-multipart==0.0.12
pytorch-lightning==2.4.0
pytz==2024.2
pyworld==0.3.4
PyYAML==6.0.2
questionary==1.10.0
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
resampy==0.4.3
rich==13.9.3
rpds-py==0.20.0
ruff==0.7.1
safehttpx==0.1.1
scikit-learn==1.5.2
scipy==1.14.1
semantic-version==2.10.0
sh==2.1.0
shellingham==1.5.4
simple-term-menu==1.5.2
six==1.16.0
sniffio==1.3.1
soundfile==0.12.1
starlette==0.41.2
sympy==1.13.3
tabulate==0.9.0
tensorboard==2.18.0
tensorboard-data-server==0.7.2
termcolor==2.3.0
text-unidecode==1.3
threadpoolctl==3.5.0
tomli==2.0.2
tomlkit==0.12.0
torch==2.1.0+cu118
torchaudio==2.1.0+cu118
torchinfo==1.8.0
torchmetrics==1.5.1
tqdm==4.66.6
triton==2.1.0
typer==0.12.5
types-python-dateutil==2.9.0.20241003
types-PyYAML==6.0.12.20240917
types-requests==2.32.0.20241016
types-setuptools==75.2.0.20241025
types-tabulate==0.9.0.0
types-tqdm==4.66.0.20240417
typing_extensions==4.12.2
tzdata==2024.2
unicodecsv==0.14.1
urllib3==2.2.3
uvicorn==0.32.0
virtualenv==20.27.1
wcwidth==0.2.13
websockets==12.0
Werkzeug==3.0.6
yarl==1.17.0
yaspin==3.1.0

```

**Review by marctessier — APPROVED** [review]
Look Good Eric. Works great!

**Comment by joanise** [comment]
Updated. Output now looks like this:
```
EveryVoice Diagnostic information
EveryVoice version: 0.1.0a3
Python version: 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:24:24) [GCC 13.3.0]
System: Linux 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64

*torch* modules installed using pip:
pytorch-lightning==2.4.0
torch==2.1.0+cu118
torchaudio==2.1.0+cu118
torchinfo==1.8.0
torchmetrics==1.5.1

Other modules installed using pip:
absl-py==2.1.0
aiofiles==23.2.1
[...]
yarl==1.16.0
yaspin==3.1.0

Modules installed using conda:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
[...]
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
```

It's a total of 310 lines longs in my current terminal.

I wanted to highlight torch version early, and since we install sox using conda it seemed important to list those deps too.

**Comment by marctessier** [comment]
Confirming  @joanise  that is what I am seeing now  and great Idea :-)   I like how conda / pip stuff is separated. 

I am using u20,  I am getting a total of 300 lines. ( including everything / even empty lines from that output)

```
(EveryVoice_ej_549) $ everyvoice -d | wc -l
300
```

```
(EveryVoice_ej_549) $ everyvoice -v
0.1.0a3
(EveryVoice_ej_549) $ everyvoice -d
EveryVoice Diagnostic information
EveryVoice version: 0.1.0a3
Python version: 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:24:24) [GCC 13.3.0]
System: Linux 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64

*torch* modules installed using pip:
pytorch-lightning==2.4.0
torch==2.1.0+cu118
torchaudio==2.1.0+cu118
torchinfo==1.8.0
torchmetrics==1.5.1

Other modules installed using pip:
absl-py==2.1.0
aiofiles==23.2.1
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.6.2.post1
...
yaspin==3.1.0

Modules installed using conda:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aom                       3.9.1                hac33072_0    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
dav1d                     1.2.1                hd590300_0    conda-forge
ffmpeg                    7.1.0           gpl_he2fd91e_702    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h7e30c49_1    conda-forge
...
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

```

**Comment by roedoejet** [comment]
this is awesome @joanise !

**Pull request merged**
