### PR TITLE
fix(wizard): fixes non-updating keyword of text in data dictionary

### PR DESCRIPTION
**Pull request by wiitt**
Although the bug majorly affected festival data only, updating 'text' keyword is done in general way now. So, if sv-like data is read into dict, it should work well. Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/496

### PR Goal? 
Makes the wizard work for festival data format.

### Fixes? 
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/496

### Feedback sought? 
Check if it works.

### Priority? 
Medium. Blocks testing of the developed solution for the issue https://github.com/EveryVoiceTTS/EveryVoice/issues/470.

### Tests added? 
Added a new complete-tour wizard test for data in the festival format.

### How to test? 
Try to create a new project with a filelist in a festival format.

### Confidence? 
High. Quite a minor fix.

### Version change? 
Probably, yes. Depends on how important the ability of work with data in the festival format is.

### Related PRs? 
No

### CODE REVIEW

**Comment by joanise** [comment]
The code looks straightforward, so I'm almost ready to approve, with two caveats:
 - if you're willing to add unit testing for it, that would be great (but you can punt and ask me to do it, that's OK too), 
 - CI fails. That's not good, but it may not be your code, so I'm testing that. I'll approve as is if the CI failure is unrelated. We need to fix CI but that's not on you.

**Review by roedoejet — CHANGES_REQUESTED** [review]
Thanks for fixing this @wiitt ! Yes, @joanise, adding a test would be great. @wiitt, you and I can walk through that tomorrow if you like. You'll also need to rebase this onto main to get CI to pass now that @joanise as merged his patch. Thanks all!

**Comment by wiitt** [comment]
Thanks @roedoejet! Yes, this would be great. I'm working on tests already, @joanise kindly explained me how to work with the tests. So, I'll probably have something done by tomorrow, and we can take a look at it, fix flaws and maybe get ideas what to improve.

**Comment by roedoejet** [comment]
> Thanks @roedoejet! Yes, this would be great. I'm working on tests already, @joanise kindly explained to me how to work with the tests. So, I'll probably have something done by tomorrow, and we can take a look at it, fix flaws and maybe get ideas what to improve.

you and @joanise are both awesome! thanks so much. yes we can chat tomorrow about it.

**Review by roedoejet — APPROVED** [review]
looks good to me, thanks for adding the test @wiitt !

**Pull request merged**
