### PR TITLE
add allowlist and denylist options to demo

### LINKED ISSUE #485: create allowlist/denylist for allowed/disallowed words for synthesis
We should be able to limit the words that someone can synthesize using the demo both by providing an allowlist option (where any words not in the allowlist cannot be generated) and a denylist (where any words in the denylist cannot be generated).

### PR DESCRIPTION
**Pull request by roedoejet**
fixes #485

### PR Goal? 

Allow basic allowlist/denylist functionality in demo. If an allowlist is supplied, then only those words/utterances are allowed to be synthesized. If a denylist is supplied, then only words/utterances not on the denylist are allowed to be synthesized. The former is more secure since it is more restricted. The latter can be hacked (I've done Unicode normalization to prevent Unicode homograph attacks, but there are a lot of other possible attacks, probably beyond scope of this PR).

### Fixes? 

#485

### Feedback sought? 

Sanity. Any improvements to make this more secure would be appreciated; there are a lot of hacks to get around the denylist at least. Some ideas may be able to be incorporated into this PR if they're easy enough, otherwise we can create issues.

### Priority? 

0.1.0a5

### Tests added? 

No tests available for the demo.

### How to test? 

create a plain text file and pass it through when running the demo (`everyvoice demo fp.ckpt vocoder.ckpt --allowlist path_to_allowlist.txt`) Then only those words should be able to be synthesized. Everything else should throw an error in the demo GUI and through the API

### Confidence? 

Medium

### Version change? 

no

### Related PRs? 

none

### CODE REVIEW

**Review by joanise — COMMENTED** [review]
Looks pretty straightforward, but also minimalist, is the feature requirement really that simple? For morphologically complex languages, this will be nearly impossible to use. And the deny list option will have little effect since it's trivial to circumvent with minor typos.

In any case, I didn't test this, but the code looks OK to me given the simple feature this PR implements.

**Comment by dlothian** [comment]
> Looks pretty straightforward, but also minimalist, is the feature requirement really that simple? For morphologically complex languages, this will be nearly impossible to use. And the deny list option will have little effect since it's trivial to circumvent with minor typos.
> 
> In any case, I didn't test this, but the code looks OK to me given the simple feature this PR implements.

- To address it not working for morphologically complex languages, could it also be set up to accept regex in the allow/deny list? And then instead of checking if it's an exact substring of the submitted text you could re.match it. Verbatim substring matching can also lead to a lot of false positive, see: [The Scunthorpe Problem](https://en.wikipedia.org/wiki/Scunthorpe_problem) 
- Both the submitted text and the allow/deny are normalized but is case handled? Not as familiar with the code base yet so not sure if this is handled elsewhere.

**Comment by marctessier** [comment]
I tested.  the Deny and Allow list  and by principle it all works.   BUT things need to be exact matches.   Like we were talking earlier could be a bit better  . EX:   case insensitive ,  ignore symbols ?

```
cat allowlist.txt 
This is a test
hello
world
Hello World
```
Is this example,   " `This is a test `" worked :-)        but not this  becasue of the period at end -->  " `This is a test.` "    or  this  even if all words are in the list but separated on 2 lines.. (  -->  " `This is a test world`"

The same could be  applied to the denylist.. 

We can approve this pull  as-is  and open a new "improvement" issue , this pull  does answer the "spirit" of the intention of what is  requested and works!  Your call  @roedoejet

**Comment by marctessier** [comment]
I forgot to add that some of  the error log printing could be omited and only keep the last printed line..  ( the Oops, with the offending  transaction. )  The rest of the traceback information  is not needed / add noise to the logs...


```
 Traceback (most recent call last):
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/home/tessierm/SANDBOX/EveryVoice/everyvoice/demo/app.py", line 49, in synthesize_audio
    raise gr.Error(
gradio.exceptions.Error: 'Oops, the word world , is not allowed to be synthesized by this model. Please contact the model owner.'
```

**Comment by marctessier** [comment]
I forgot to add that some of  the error log printing could be omited and only keep the last printed line..  ( the Oops, with the offending  transaction. )  The rest of the traceback information  is not needed / add noise to the logs...


```
 Traceback (most recent call last):
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/tessierm/miniforge3/envs/ev_dev.ap_485/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/home/tessierm/SANDBOX/EveryVoice/everyvoice/demo/app.py", line 49, in synthesize_audio
    raise gr.Error(
gradio.exceptions.Error: 'Oops, the word world , is not allowed to be synthesized by this model. Please contact the model owner.'
```

**Comment by roedoejet** [comment]
Thanks so much for this y'all! I've added case sensitivity, word tokenization for the denylist, punctuation removal, and duplicate character attack prevention. This should be a bit better. Did you end up checking the speed with a large allow/deny list @marctessier ?

**Comment by marctessier** [comment]
No not yet , thanks for the reminder. ... I will prep a couple test for that and compare the timing in a few minutes.

**Comment by marctessier** [comment]
OK @roedoejet , I just ran a couple  test where I concatenated the text  data from the LJ metadata.psv and also using the linux DIC file together.   Good news, I am not noticing a difference in processing time when using it as a deny or allow list.   This currently has over 300k words / 115k entries.  In principle this is good to go as a first release.. The only annoying thing I mentioned earlier  is the "traceback" information getting displayed in the logs for every  "Ooops" entry.  Possibly also the symbols that need to be defined (  " .  , ? ! ...etc...)

Also every successful  gets printed in the logs...  Is this "Ok"  or did we want this information  to be anonymous? 
ex: 
`Processing text ['This is a test with the deny list.'] `

```
(ev_dev.ap_485) tessierm@dl-15:~/DEMO_LJ_TEST$ wc -l -w words.allow 
 115501  324925 words.allow
```

**Comment by roedoejet** [comment]
> OK @roedoejet , I just ran a couple test where I concatenated the text data from the LJ metadata.psv and also using the linux DIC file together. Good news, I am not noticing a difference in processing time when using it as a deny or allow list. This currently has over 300k words / 115k entries. In principle this is good to go as a first release.. The only annoying thing I mentioned earlier is the "traceback" information getting displayed in the logs for every "Ooops" entry. Possibly also the symbols that need to be defined ( " . , ? ! ...etc...)
> 
> Also every successful gets printed in the logs... Is this "Ok" or did we want this information to be anonymous? ex: `Processing text ['This is a test with the deny list.'] `
> 
> ```
> (ev_dev.ap_485) tessierm@dl-15:~/DEMO_LJ_TEST$ wc -l -w words.allow 
>  115501  324925 words.allow
> ```

Thanks Marc! Unfortunately I don't think we can change the traceback issue since it's just how gradio handles errors. Silencing that would require implementing our own toast messages about the error etc.

**Pull request merged**
